# Troubleshooting RAG Configuration
app:
  name: "Troubleshooting RAG"
  version: "1.0.0"
  debug: true

data_sources:
  enabled:
    - tickets
    - slack
    - logs
    - documentation
  
  tickets:
    file_patterns: ["*.csv", "*.xlsx"]
    date_columns: ["created_date", "resolved_date"]
    required_columns: ["id", "description", "resolution"]
  
  slack:
    file_patterns: ["*.json"]
    channels: ["#it-support", "#infrastructure", "#alerts"]
  
  logs:
    file_patterns: ["*.log", "*.txt"]
    error_patterns: ["ERROR", "WARN", "CRITICAL", "FATAL"]
  
  documentation:
    file_patterns: ["*.md", "*.txt", "*.docx"]

vector_store:
  type: "chromadb"
  persist_directory: "./data/vector_db"
  collection_name: "troubleshooting_knowledge"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

processing:
  chunk_size: 512
  chunk_overlap: 50
  batch_size: 100
  max_chunks_per_document: 50

gui:
  window_size: "1000x700"
  theme: "default"
  font_family: "Arial"
  font_size: 10
