#!/bin/bash
# Interactive PaaS Setup Script
# This script guides users through configuration and generates .env file

set -e

echo "=========================================="
echo "  Troubleshooting AI - PaaS Setup"
echo "=========================================="
echo ""
echo "This script will help you configure your deployment."
echo "Press Enter to use default values (shown in brackets)."
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to generate secure random string
generate_secret() {
    python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || \
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
}

# Function to generate Fernet key
generate_fernet_key() {
    python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || \
    echo "ERROR: Python cryptography library required"
}

# Function to validate input
validate_not_empty() {
    if [ -z "$1" ]; then
        echo -e "${RED}Error: This field cannot be empty${NC}"
        return 1
    fi
    return 0
}

# Navigate to backend directory
cd "$(dirname "$0")/../backend" || exit 1

# Check if .env already exists
if [ -f ".env" ]; then
    echo -e "${YELLOW}Warning: .env file already exists${NC}"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "Setup cancelled."
        exit 0
    fi
    cp .env .env.backup.$(date +%Y%m%d_%H%M%S)
    echo "Backed up existing .env file"
    echo ""
fi

# Start configuration
echo "=== Database Configuration ==="
read -p "Database URL [postgresql://postgres:password@localhost:5432/troubleshooting_ai]: " DATABASE_URL
DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@localhost:5432/troubleshooting_ai}

echo ""
echo "=== Security Configuration ==="
echo "Generating secure keys..."
SECRET_KEY=$(generate_secret)
CREDENTIAL_ENCRYPTION_KEY=$(generate_fernet_key)

if [[ "$CREDENTIAL_ENCRYPTION_KEY" == *"ERROR"* ]]; then
    echo -e "${YELLOW}Warning: Could not auto-generate Fernet key${NC}"
    read -p "Enter CREDENTIAL_ENCRYPTION_KEY (or press Enter to skip): " CREDENTIAL_ENCRYPTION_KEY
    if [ -z "$CREDENTIAL_ENCRYPTION_KEY" ]; then
        echo -e "${YELLOW}You'll need to set CREDENTIAL_ENCRYPTION_KEY manually${NC}"
    fi
fi

echo ""
echo "=== Environment Configuration ==="
read -p "Environment (development/staging/production) [production]: " ENVIRONMENT
ENVIRONMENT=${ENVIRONMENT:-production}

read -p "Enable DEBUG mode? (y/N): " DEBUG_INPUT
if [ "$DEBUG_INPUT" = "y" ] || [ "$DEBUG_INPUT" = "Y" ]; then
    DEBUG="true"
else
    DEBUG="false"
fi

echo ""
echo "=== LLM Configuration ==="
read -p "LLM Provider (llamacpp/openai/anthropic) [llamacpp]: " LLM_PROVIDER
LLM_PROVIDER=${LLM_PROVIDER:-llamacpp}

read -p "LLM Base URL [http://localhost:11434]: " LLM_BASE_URL
LLM_BASE_URL=${LLM_BASE_URL:-http://localhost:11434}

read -p "LLM Model [llama3.1:8b]: " LLM_MODEL
LLM_MODEL=${LLM_MODEL:-llama3.1:8b}

echo ""
echo "=== Optional: External APIs ==="
read -p "Perplexity API Key (optional, press Enter to skip): " PERPLEXITY_API_KEY

echo ""
echo "=== Frontend Configuration ==="
read -p "Frontend Base URL [http://localhost:3000]: " FRONTEND_BASE_URL
FRONTEND_BASE_URL=${FRONTEND_BASE_URL:-http://localhost:3000}

read -p "Backend Base URL [http://localhost:8000]: " BACKEND_BASE_URL
BACKEND_BASE_URL=${BACKEND_BASE_URL:-http://localhost:8000}

# Build ALLOWED_HOSTS
echo ""
echo "=== CORS Configuration ==="
read -p "Additional allowed hosts (comma-separated, press Enter for defaults): " ADDITIONAL_HOSTS
ALLOWED_HOSTS="[\"${FRONTEND_BASE_URL}\",\"${BACKEND_BASE_URL}\""
if [ -n "$ADDITIONAL_HOSTS" ]; then
    IFS=',' read -ra HOSTS <<< "$ADDITIONAL_HOSTS"
    for host in "${HOSTS[@]}"; do
        ALLOWED_HOSTS="${ALLOWED_HOSTS},\"$(echo $host | xargs)\""
    done
fi
ALLOWED_HOSTS="${ALLOWED_HOSTS}]"

# Generate .env file
echo ""
echo "=== Generating .env file ==="

cat > .env << EOF
# Database Configuration
# Generated by setup-paas.sh on $(date)
DATABASE_URL=${DATABASE_URL}

# Security
# IMPORTANT: Keep these secret! Do not commit to version control.
SECRET_KEY=${SECRET_KEY}
CREDENTIAL_ENCRYPTION_KEY=${CREDENTIAL_ENCRYPTION_KEY}

ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# Environment
ENVIRONMENT=${ENVIRONMENT}
DEBUG=${DEBUG}

# CORS
ALLOWED_HOSTS=${ALLOWED_HOSTS}

# Vector Store
EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
EMBEDDING_DIMENSION=384
CHUNK_SIZE=512
CHUNK_OVERLAP=50

# LLM
LLM_PROVIDER=${LLM_PROVIDER}
LLM_MODEL=${LLM_MODEL}
LLM_BASE_URL=${LLM_BASE_URL}

# Perplexity API (optional)
PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-}

# File Upload
MAX_FILE_SIZE=104857600
UPLOAD_DIR=uploads

# Multi-tenant
DEFAULT_TENANT=default
DEFAULT_TENANT_ID=1

# Queue / Streaming
REDIS_URL=redis://localhost:6379/0
REDIS_STREAM_ASSIGN=session.assign
REDIS_STREAM_COMMAND=session.command
REDIS_STREAM_RESULT=session.result
REDIS_STREAM_EVENTS=session.events
WORKER_ORCHESTRATION_ENABLED=true

# URLs
FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
BACKEND_BASE_URL=${BACKEND_BASE_URL}
OAUTH_CALLBACK_URL=${BACKEND_BASE_URL}/oauth/callback
EOF

echo -e "${GREEN}✓ .env file created successfully!${NC}"
echo ""
echo "=== Next Steps ==="
echo "1. Review the generated .env file: cat backend/.env"
echo "2. Update any values if needed"
echo "3. Start your deployment:"
echo "   docker-compose -f docker-compose.optimized.yml up -d"
echo ""
echo -e "${GREEN}Setup complete!${NC}"








