"""
Setup and configuration status endpoints
Used for first-run setup UI and configuration validation
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import Dict, Any, Optional
import os
from pathlib import Path

from app.core.database import get_db
from app.core.config import settings
from app.core.logging import get_logger

router = APIRouter()
logger = get_logger(__name__)


@router.get("/config/status")
async def get_configuration_status(
    db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """
    Check configuration status - used by first-run setup UI
    
    Returns:
    - is_configured: Whether essential config is present
    - missing_fields: List of missing required fields
    - warnings: List of configuration warnings
    - database_status: Database connection status
    """
    status = {
        "is_configured": True,
        "missing_fields": [],
        "warnings": [],
        "database_status": "unknown",
        "setup_required": False
    }
    
    # Check required configuration fields
    required_fields = {
        "SECRET_KEY": settings.SECRET_KEY,
        "DATABASE_URL": settings.DATABASE_URL,
        "CREDENTIAL_ENCRYPTION_KEY": settings.CREDENTIAL_ENCRYPTION_KEY,
    }
    
    for field_name, field_value in required_fields.items():
        if not field_value or field_value.startswith("CHANGE_ME") or field_value.startswith("your-"):
            status["missing_fields"].append(field_name)
            status["is_configured"] = False
    
    # Check database connection
    try:
        from sqlalchemy import text
        db.execute(text("SELECT 1"))
        status["database_status"] = "connected"
        
        # Check if tables exist
        try:
            db.execute(text("SELECT COUNT(*) FROM tenants"))
            status["database_status"] = "ready"
        except Exception:
            status["database_status"] = "connected_but_not_initialized"
            status["warnings"].append("Database connected but tables not initialized. Run migrations.")
    except Exception as e:
        status["database_status"] = "disconnected"
        status["warnings"].append(f"Database connection failed: {str(e)}")
        status["is_configured"] = False
    
    # Check for default/placeholder values
    if settings.SECRET_KEY and len(settings.SECRET_KEY) < 32:
        status["warnings"].append("SECRET_KEY is too short (should be 32+ characters)")
    
    if settings.ENVIRONMENT == "development" and settings.DEBUG:
        status["warnings"].append("Running in development mode with DEBUG enabled (not recommended for production)")
    
    # Check if .env file exists
    env_file = Path("backend/.env")
    if not env_file.exists():
        env_file = Path(".env")
    
    if not env_file.exists():
        status["warnings"].append(".env file not found - using environment variables only")
    
    # Determine if setup is required
    status["setup_required"] = (
        len(status["missing_fields"]) > 0 or 
        status["database_status"] in ["disconnected", "connected_but_not_initialized"]
    )
    
    return status


@router.get("/config/required-fields")
async def get_required_fields() -> Dict[str, Any]:
    """
    Get list of required configuration fields with descriptions
    Used by setup UI to show what needs to be configured
    """
    return {
        "required_fields": [
            {
                "name": "DATABASE_URL",
                "description": "PostgreSQL database connection string",
                "example": "postgresql://user:password@localhost:5432/troubleshooting_ai",
                "required": True
            },
            {
                "name": "SECRET_KEY",
                "description": "Secret key for JWT token signing (32+ characters)",
                "example": "Generated by setup script",
                "required": True,
                "auto_generated": True
            },
            {
                "name": "CREDENTIAL_ENCRYPTION_KEY",
                "description": "Fernet key for encrypting stored credentials",
                "example": "Generated by setup script",
                "required": True,
                "auto_generated": True
            },
            {
                "name": "ENVIRONMENT",
                "description": "Environment: development, staging, or production",
                "example": "production",
                "required": False,
                "default": "development"
            },
            {
                "name": "LLM_BASE_URL",
                "description": "Base URL for LLM service (e.g., Ollama)",
                "example": "http://localhost:11434",
                "required": False,
                "default": "http://localhost:11434"
            },
            {
                "name": "ALLOWED_HOSTS",
                "description": "Comma-separated list of allowed CORS origins",
                "example": '["http://localhost:3000", "https://yourdomain.com"]',
                "required": False,
                "default": '["http://localhost:3000"]'
            }
        ],
        "optional_fields": [
            {
                "name": "PERPLEXITY_API_KEY",
                "description": "Perplexity API key for web search (optional)",
                "example": "pplx-...",
                "required": False
            },
            {
                "name": "REDIS_URL",
                "description": "Redis connection URL (defaults to localhost)",
                "example": "redis://localhost:6379/0",
                "required": False,
                "default": "redis://localhost:6379/0"
            }
        ]
    }








